#!/usr/bin/env bash

function _nt_list() {
    while read name dummy ; do
        echo ${name//:*}
    done < <(tmux list-sessions 2>/dev/null)
}


function _complete_nt() {
	local cur prev opts
	COMPREPLY=()
	cur="${COMP_WORDS[COMP_CWORD]}"
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	opts=$(_nt_list)
	COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
	return 0
}

complete -F _complete_nt nt
